# Indentation settings
indent_type = "Spaces"     # Use spaces for indentation
indent_width = 2           # Use 2 spaces per indentation level
column_width = 120         # Maximum line length

# String formatting
quote_style = "AutoPreferDouble"  # Prefer double quotes but keep existing when mixed

# Import sorting
[sort_requires]
enabled = true        # Sort require statements
