#!/usr/bin/env bash

declare -r XDG_STATE_HOME="${XDG_STATE_HOME:-"$HOME/.local/state"}"
declare -r XDG_DATA_HOME="${XDG_DATA_HOME:-"$HOME/.local/share"}"
declare -r XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"
declare -r XDG_CACHE_HOME="${XDG_CACHE_HOME:-"$HOME/.cache"}"

export ANONVIM_RUNTIME_DIR="${ANONVIM_RUNTIME_DIR:-"$XDG_DATA_HOME/anonvim"}"
export ANONVIM_CONFIG_DIR="${ANONVIM_CONFIG_DIR:-"$XDG_CONFIG_HOME/avim"}"
export ANONVIM_STATE_DIR="${ANONVIM_STATE_DIR:-"$XDG_STATE_HOME/avim"}"
export ANONVIM_CACHE_DIR="${ANONVIM_CACHE_DIR:-"$XDG_CACHE_HOME/avim"}"

export ANONVIM_BASE_DIR="${ANONVIM_BASE_DIR:-$ANONVIM_RUNTIME_DIR/avim}"

exec nvim -u "$ANONVIM_BASE_DIR/init.lua" "$@"
