# Luacheck configuration for AnoNvim
# Reference: https://luacheck.readthedocs.io/en/stable/config.html

# Lua version and standards
std = "lua51+nvim"

# Performance settings
cache = true                # Enable caching
max_cyclomatic_complexity = 20  # Maximum function complexity

# Code style
max_line_length = false     # Disable line length warnings
max_code_line_length = 120  # But set a soft limit
max_string_line_length = 120
max_comment_line_length = 120

# Method handling
self = false               # Don't report unused self arguments

# Specific ignores
ignore = {
  "631",                   # Line length limit
  "212/_.*",              # Unused arguments starting with _
  "213/_.*",              # Unused loop variables starting with _
  "542",                  # Empty if branch
  "211/_.*",              # Unused variable starting with _
}

# Files to exclude
exclude_files = {
  "lua/avim/lazy/**",     # Plugin manager files
  "tests/**",             # Test files
  ".luacheckrc",          # This config file
}

# Custom file patterns
files = {
  ["lua/avim/plugins/*.lua"] = {
    enable = {"631"},      # Enable line length checks for plugins
  },
  ["lua/avim/core/*.lua"] = {
    max_cyclomatic_complexity = 25,  # Allow more complexity in core
  },
}
