# Selene configuration for AnoNvim
# Reference: https://kampfkarren.github.io/selene/usage/configuration.html

# Use Vim standard library
std = "vim"

# Rule configurations
[rules]
# Allow using global variables (needed for Neovim API)
global_usage = "allow"

# Allow multiple statements on one line (for compact code)
multiple_statements = "allow"

# Allow non-standard library usage (needed for Neovim API)
incorrect_standard_library_use = "allow"

# Allow mixed table types (common in Neovim configs)
mixed_table = "allow"

# Additional rules for better code quality
empty_if = "warn"              # Warn about empty if statements
shadowing = "warn"             # Warn about shadowing variables
undefined_variable = "warn"    # Warn about undefined variables
unused_variable = "warn"       # Warn about unused variables
